name: Bug Report
description: Report a bug
labels: kind/bug
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues to avoid creating duplicates.

  - type: textarea
    id: problem
    attributes:
      label: What happened? What is the problem?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: example-url
    attributes:
      label: Example URL(s)
      description: Please provide URL(s) with example of the issue.
    validations:
      required: false

  - type: textarea
    id: reproducer
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
      render: bash
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Workaround
      options:
        - label: There is an existing workaround that can be used until this issue is fixed.
          required: false

  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request for this issue. (Packit team is happy to help!)
          required: false
