name: Check release notes in the PR description

on:
  workflow_call:
    inputs:
      description:
        required: true
        type: string
      placeholder:
        required: false
        type: string
        default: "Packit now supports automatic ordering of ☕ after all checks pass."

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Check if there are any release release notes and placeholder
        env:
          PR_DESCRIPTION: ${{ inputs.description }}
          NOTES_PLACEHOLDER: ${{ inputs.placeholder }}
        shell: python
        run: |
          import os
          import re

          RELEASE_NOTES_TAG = "RELEASE NOTES"
          PLACEHOLDER_REGEX = (
              f'\\s*(TBD|TODO|FIXME|XXX|{os.getenv("NOTES_PLACEHOLDER")})\\s*'
          )


          description = os.getenv("PR_DESCRIPTION")
          if f"{RELEASE_NOTES_TAG} BEGIN" in description:
              print("::notice::Release notes are present.")
          else:
              print("::warning::Release notes are not present.")
              exit()

          if re.search(
              (
                  f"{RELEASE_NOTES_TAG} BEGIN\r?\n"
                  f"{PLACEHOLDER_REGEX}\r?\n"
                  f"{RELEASE_NOTES_TAG} END"
              ),
              description,
          ):
              print("::error::Release notes are still not written.")
              exit(1)
          else:
              print("::debug::Release notes placeholder has not been found.")
